# Generated by Django 4.0 on 2022-07-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('phone', models.IntegerField(max_length=220)),
                ('textarea', models.CharField(max_length=300)),
            ],
        ),
    ]
