# Generated by Django 4.0 on 2022-07-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_suggest_smessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggest',
            name='smessage',
            field=models.TextField(max_length=500),
        ),
    ]
